package com.partime.user.Constants

interface Constants {

    companion object {

        val FORGOT_TYPE = "forgot_type"
        val USER_NAME = "USER_NAME"
        val USER_EMAIL = "USER_EMAIL"

        val JOB_LIST = "JOB_LIST"
        val JOB_ID = "JOB_ID"

        val PROFILE_RESPONSE = "PROFIE_RESPONSE"
        val EDIT_PROFILE_RESPONSE = "EDIT_PROFILE_RESPONSE"


        val BROADCAST_HOME = "BROADCAST_HOME"

        val FROM = "FROM"
        val SJ_APPLY_STATUS = "SJ_APPLY_STATUS"
        val SJ_SAVE_STATUS = "SJ_SAVE_STATUS"
        val SJ_ID = "SJ_ID"
        val SJ_JOB_STATUS = "JOB_STATUS"
        val SJ_JOB_TYPE = "JOB_TYPE"

        val HOME_APPLY_STATUS = "HOME_APPLY_STATUS"
        val HOME_SAVE_STATUS = "HOME_SAVE_STATUS"
        val HOME_ID = "HOME_ID"
        val HOME_JOB_STATUS = "JOB_STATUS"
        val HOME_JOB_TYPE = "JOB_TYPE"

        val DOCUMENTS = "DOCUMENTS"

        val DOC_NAME = "DOC_NAME"

        val BRODCAST_SAVED_JOB = "BRODCAST_SAVED_JOB"
        val SAVED_APPLY_STATUS = "SAVED_APPLY_STATUS"
        val SAVED_SAVE_STATUS = "SAVED_SAVE_STATUS"
        val SAVED_ID = "SAVED_ID"
        val SAVED_JOB_STATUS = "SAVED_JOB_STATUS"
        val SAVED_JOB_TYPE = "SAVED_JOB_TYPE"

        val INDUSTRY_FILTERS = "INDUSTRY_FILTERS"
        val COMPANY_FILTERS = "COMPANY_FILTERS"
        val JOBTYPE_FILTER = "JOBTYPE_FILTER"
        val HOURS_RATE_FILTERS = "HOURS_RATE_FILTERS"
        val HOURS_PER_WEEK = "HOURS_PER_WEEK"
        val JOB_TITLE_FILTERS = "JOB_TITLE_FILTERS"
        val COUNTRIES_FILTERS = "COUNTRIES_FILTERS"
        val STATES_FILTERS = "STATES_FILTERS"
        val CITIES_FILTERS = "CITIES_FILTERS"

        val INDUSTRIES_SELECTED = "INDUSTRIES_SELECTED"
        val COMPANY_SELECTED = "COMPANY_SELECTED"
        val HOURS_RATE_SELECTED = "HOURS_RATE_SELECTED"
        val HOURS_WEEK_SELECTED = "HOURS_WEEK_SELECTED"
        val JOB_TITLE_SELECTED = "JOB_TITLE_SELECTED"
        val COUNTRIES_SELECTED = "COUNTRIES_SELECTED"
        val STATES_SELECTED = "STATES_SELECTED"
        val CITIES_SELECTED = "CITIES_SELECTED"


        val INDUSTRIES = "INDUSTRIES"
        val COMPANY = "COMPANY"
        val HOURS_RATE = "HOURS_RATE"
        val HOURS_WEEK = "HOURS_WEEK"
        val JOB_TITLE = "JOB_TITLE"
        val JOB_TYPE = "JOB_TYPE"
        val COUNTRIES = "COUNTRIES"
        val STATES = "STATES"
        val CITIES = "CITIES"

        val SELECTED_COUNTRY = "SELECTED_COUNTRY"
        val SELECTED_STATE = "SELECTED_STATE"

        val COUNTRY_SELECTED = "COUNTRY_SELECTED"
        val STATE_SELECTED = "STATE_SELECTED"
        val CITY_SELECTED = "CITY_SELECTED"

        val COUNRTY = "COUNRTY"
        val STATE = "STATE"
        val CITY = "CITY"

        val CURRENT_ADDRESS = "CURRENT_ADDRESS"
        val CURRENT_ADDRESS_SELECTED = "CURRENT_ADDRESS_SELECTED"

        val RECIEVER_ID = "RECIEVER_ID"
        val SENDER_PROFILE_PICTURE = "SENDER_PROFILE_PICTURE"
        val SENDER_NAME = "SENDER_NAME"

        val UNREAD_NOTIFICATION_COUNT = "UNREAD_NOTIFICATION_COUNT"

        /*val MAP_JOB_ID="MAP_JOB_ID"
        val SAVE_JOB_MAP_BROADCAST="SAVE_JOB_MAP_BROADCAST"
        val SAVE_STATUS_MAP="SAVE_STATUS_MAP"
        val APPLY_JOB_MAP_BROADCAST="APPLY_JOB_MAP_BROADCAST"
        val APPLY_STATUS_MAP="APPLY_STATUS_MAP"*/

        //for filters on map.......
        val MAP_INDUSTRY_FILTERS = ""
        val MAP_COMPANY_FILTERS = ""
        val MAP_JOBTYPE_FILTER = ""
        val MAP_HOURS_RATE_FILTERS = ""
        val MAP_HOURS_PER_WEEK = ""
        val MAP_JOB_TITLE_FILTERS = ""
        val MAP_COUNTRIES_FILTERS = ""
        val MAP_STATES_FILTERS = ""
        val MAP_CITIES_FILTERS = ""
        val MAP_CURRENT_ADDRESS_FILTER = ""

        val BROADCAST_FILTER_MAP = "BROADCAST_FILTER_MAP"
        val FILTERS = "FILTERS"

        //for task detail...
        val TASK_ID = "TASK_ID"

        val TASK_DESCRIPTION_ID = ""
        val TASK_DESCRIPTION_STATUS = ""

        val MONTH_NO="MONTH_NO"
        val SELECTED_MONTH="SELECTED_MONTH"
        val SELECTED_YEAR=""

        val TASK_LIST = "TASK_LIST"


    }
}